# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'JWBestPracticeApps' do

pod 'JWPlayer-SDK', '~> 2.0'

end

target 'JWCasting' do

pod 'JWPlayer-SDK', '~> 2.0'
pod 'google-cast-sdk', '<= 2.10.0.4070'

end

target 'JWAirPlay' do

pod 'JWPlayer-SDK', '~> 2.0'

end

target 'JWRemotePlayer' do

pod 'JWPlayer-SDK', '~> 2.0'
pod 'google-cast-sdk', '<= 2.10.0.4070'

end

target 'JWRemoteController' do

end

target 'JWRemoteController Extension' do

end

target 'JWRemoteCastPlayer' do

pod 'JWPlayer-SDK', '~> 2.0'
pod 'google-cast-sdk', '<= 2.10.0.4070'

end

target 'JWRemoteCastController' do

end

target 'JWRemoteCastController Extension' do

end

target 'JWFairPlayDrm’ do

pod 'JWPlayer-SDK', '~> 2.0'

end

workspace 'JWBestPracticeApps'

